import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <head>
        {/* 💡 [최종 병기] 어떤 JS 번들이 실행되기 전에 0순위로 실행되는 인라인 스크립트 주입 */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                if (typeof window !== 'undefined') {
                  if (!window.matchMedia) {
                    window.matchMedia = function() {
                      return {
                        matches: false,
                        media: '',
                        onchange: null,
                        addListener: function() {},
                        removeListener: function() {},
                        addEventListener: function() {},
                        removeEventListener: function() {},
                        dispatchEvent: function() { return false; }
                      };
                    };
                  } else {
                    var mql = window.matchMedia('()');
                    if (!mql.addListener) {
                      var originalMatchMedia = window.matchMedia;
                      window.matchMedia = function(query) {
                        var mql = originalMatchMedia(query);
                        if (!mql.addListener) { mql.addListener = function(l) { mql.addEventListener('change', l); }; }
                        if (!mql.removeListener) { mql.removeListener = function(l) { mql.removeEventListener('change', l); }; }
                        return mql;
                      };
                    }
                  }
                }
              })();
            `,
          }}
        />
      </head>
      <body className="min-h-full flex flex-col">
        {children}
      </body>
    </html>
  );
}